### ISSUE TITLE
add webfont-loader option

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [devinehowest/generator-devine-boilerplate#28]
Enable webfont-loader in a correct way.

**Comment by thibmaek** [comment]
Slightly OT, but what about defaulting to system font? 

- [Documentation Draft](https://webkit.org/blog/3709/using-the-system-font-in-web-content/)
- [Spec](https://lists.w3.org/Archives/Public/www-style/2015Jul/0169.html)
- [Code snippet](https://github.com/thibmaek/thibmaek.github.io/blob/master/_sass/base/_variables.scss#L37-L38) (note that this might be too much since it tries to target every device)

**Comment by geoffreydhuyvetters** [comment]
heb gewoon wat vreemde ervaringen met die system fonts, verschillende sites zagen er met de system font echt heel lelijk uit als je niet op de laatste MacOS zit.
